#!/usr/bin/env bash
# Made by mH (https://github.com/matthmr)

while :
do

	MEM=$(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}')
	DISK=$(df -Ph | grep "/dev/sdb2" | awk '{print $3 "/" $4}')
	IP=$(nmcli -a | grep inet4 | tr '[./]' ' ' | awk '{print $4"."$5}')
	UPTIME=$(uptime -p | grep -o '[0-9]*' | tr '\n' ':')
	UPTIME=${UPTIME%:}
	
	DATE_DAY=$(date +'%d/%m/%Y %a')
	DATE_HOUR=$(date +'%I:%M %p')

	xsetroot -name "  $MEM |  $DISK |  $IP |  $UPTIME |  $DATE_DAY |  $DATE_HOUR "

	sleep 90

done
