#!/usr/bin/env bash
# Made by mH (https://github.com/matthmr)

while :
do
	MEM=$(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}')
	DISK=$(df -Ph | grep "/dev/sdb2" | awk '{print $3 "/" $4}')
	IP=$(nmcli -a | grep 'inet4 192' | awk '{print $2}' | sed 's/\/.*$//')
	DATE_DAY=$(date +'%d/%m %a')
	DATE_HOUR=$(date +'%I:%M %p')
	xsetroot -name "   $MEM |  $DISK |  $IP |  $DATE_DAY |  $DATE_HOUR "
	sleep 60
done
