#!/usr/bin/env bash
# Made by mH (https://github.com/matthmr)

# Disk
#"/dev/sda1"
#        home       ssd         root
DRIVES=("/dev/sda1" "/dev/sda2" "/dev/sdc2")
DRIVENO=${#DRIVES[@]}
DRIVEIN=$(($RANDOM % $DRIVENO))
DRIVE=${DRIVES[DRIVEIN]}
DISK=$(df -H "$DRIVE" | awk '!/^Filesystem/ {print $3 "/" $2 " ["$5"]" " ["$6"]"}')

# Volume
VOL=$(amixer get Master | grep -Eo '\[[0-9]{1,3}%\] \[\-?[0-9]{1,3}\.[0-9]{1,2}dB')
DB=${VOL/\[*%\] /}
PERC=${VOL/$DB/}
PERC=${PERC/\[/}
PERC=${PERC/\]/}
VOL="$PERC$DB+]"

# Memory
MEM=$(free -h --si | awk '/^Mem:/ {print $3 "/" $2}')
_MEM=$(free --mega | awk '/^Mem:/ {print $2 "/" $3}')
PERC=$(( 100 / ($_MEM) ))
MEM="$MEM [$PERC%]"

# Ethernet
INTERFACE="eth0"
_IP=$(ip addr show $INTERFACE | awk '/192\.168/ {print $2}')
_IP=${_IP%/*}
IP="${_IP/192.168.} [$INTERFACE]"

# Uptime
_UPTIME=$(awk -F. '{print $1}' /proc/uptime)
_MIN=$(($_UPTIME / 60))
_HOUR=$(($_MIN / 60))
_MIN=$(($_MIN % 60))
[[ $_HOUR =~ ^[0-9]$ ]] && _HOUR="0$_HOUR"
[[ $_MIN =~ ^[0-9]$ ]] && _MIN="0$_MIN"
UPTIME="$_HOUR$_MIN"

# Kernel
#_KERNEL=$(uname -r)
#KERNEL="${_KERNEL%-arch*}"

# Time
_DATE=$(date +'%a %Y%m%d %H%M')
DATE="$_DATE"

PROMPT=\
"  $IP |\
 墳 $VOL |\
  $MEM |\
  $DISK |\
  $DATE |\
  $UPTIME "

echo "$PROMPT"
