#!/usr/bin/env bash
# Made by mH (https://github.com/matthmr)

MEM=$(free -h --kilo | awk '/^Mem:/ {print $3 "/" $2}')
DISK=$(df -Ph | grep "/dev/sdb2" | awk '{print $3 "/" $2}')
# IP=$(nmcli -a | grep inet4 | tr '[./]' ' ' | awk '{print $4"."$5}')
UPTIME=$(uptime -p | grep -o '[0-9]*' | tr '\n' ':')
UPTIME=${UPTIME%:}
KERNEL=$(uname -r)
KERNEL=${KERNEL%-arch*}

DATE_DAY=$(date +'%d/%m/%Y %a')
DATE_HOUR=$(date +'%I:%M %p')

echo "  $KERNEL |  $MEM |  $DISK |  $UPTIME |  $DATE_DAY |  $DATE_HOUR "
