#!/usr/bin/env bash

#*****************************************************
# change anything that is followed by "#change this" #
#*****************************************************

# orx: override X:
#      xbindkeys command to be used with clipmenu and rofi
#      it has a orx.xbindkeysrc counterpart which is supposed
#      to be dumped into your .xbindkeys. Default key binding
#      is CONTROL+ALT+v

dir=${XDG_RUNTIME_DIR-"${TMPDIR-/tmp}"}/clipmenu.6.$USER # change this
#                                    ... but only if I've lagged behind the latest version of clipmenu

cache="$dir/line_cache"

manifest() {
    LC_ALL=C sort -rnk 1 < "$cache" | cut -d' ' -f2- | awk '!seen[$0]++'
}

HEADER=$(manifest | head -1)
clipboard=$dir/$(cksum <<< "$HEADER")

xsel --logfile /dev/null -i clipboard < "$clipboard"
